mod album_art;
mod album_cover_section;
mod album_metadata;
mod back_button;
mod delete_release_dialog;
mod error;
mod export_error_toast;
mod loading;
mod page;
mod play_album_button;
mod release_action_menu;
mod release_info_modal;
mod release_tabs_section;
mod track_row;
pub mod utils;
mod view;
mod view_files_modal;

pub use page::AlbumDetail;
pub use release_info_modal::ReleaseInfoModal;
pub use view_files_modal::ViewFilesModal;
