#ifndef BAE_STORAGE_HELPERS_H
#define BAE_STORAGE_HELPERS_H

#include <libtorrent/session.hpp>
#include <libtorrent/session_params.hpp>
#include <libtorrent/add_torrent_params.hpp>
#include <libtorrent/torrent_handle.hpp>
#include <libtorrent/io_context.hpp>
#include <libtorrent/disk_interface.hpp>
#include <functional>
#include <memory>
#include <string>

namespace libtorrent {

// Forward declarations
class disk_interface;
struct settings_interface;
struct counters;

/// Create session_params with custom disk I/O constructor
///
/// This is a helper function to create session_params and set a custom
/// disk_io_constructor, which libtorrent-rs doesn't expose.
/// disk_io_constructor is a std::function that creates a disk_interface.
std::unique_ptr<session_params> create_session_params_with_storage(
    std::function<std::unique_ptr<disk_interface>(io_context&, settings_interface const&, counters&)> disk_io_ctor
);

/// Create a session from session_params
///
/// libtorrent-rs only exposes lt_create_session() which doesn't accept params.
/// This function allows us to create a session with custom storage.
std::unique_ptr<session> create_session_with_params(
    std::unique_ptr<session_params> params
);

/// Get raw session pointer from Session unique_ptr
///
/// This allows us to extract the raw pointer to use with libtorrent-rs API
/// which expects raw pointers.
session* get_session_ptr(std::unique_ptr<session>& sess);

/// Wrapper functions for libtorrent operations using our Session type
///
/// These functions allow us to use our custom Session with libtorrent operations
/// that libtorrent-rs doesn't expose for custom sessions.

/// Parse a magnet URI and return add_torrent_params
std::unique_ptr<add_torrent_params> parse_magnet_uri(const std::string& magnet, const std::string& save_path);

/// Load a torrent file and return add_torrent_params
std::unique_ptr<add_torrent_params> load_torrent_file(const std::string& file_path, const std::string& save_path);

/// Add a torrent to a session using our Session type
torrent_handle* session_add_torrent(session* sess, std::unique_ptr<add_torrent_params>& params);

/// Get the name of a torrent from its handle (internal version)
/// Note: This is wrapped for cxx bridge - the global namespace version returns rust::String
std::string torrent_get_name_internal(torrent_handle* handle);

/// Check if a torrent has metadata available
bool torrent_has_metadata(torrent_handle* handle);

/// Get the storage index for a torrent handle
/// Returns the storage_index_t assigned by libtorrent for this torrent
int32_t torrent_get_storage_index(torrent_handle* handle);

/// Get torrent metadata for piece mapper
int32_t torrent_get_piece_length(torrent_handle* handle);
int64_t torrent_get_total_size(torrent_handle* handle);
int32_t torrent_get_num_pieces(torrent_handle* handle);

/// Check if a piece is available (downloaded and verified)
bool torrent_have_piece(torrent_handle* handle, int32_t piece_index);

/// Internal C++ struct for file info (not exposed to Rust)
struct LibTorrentFileInfo {
    int32_t index;
    std::string path;
    int64_t size;
};

/// Get the list of files in the torrent (internal C++ function)
std::vector<LibTorrentFileInfo> torrent_get_file_list_internal(torrent_handle* handle);

} // namespace libtorrent

// Type aliases for cxx bridge (must be in global namespace)
using BaeStorageConstructor = std::function<std::unique_ptr<libtorrent::disk_interface>(libtorrent::io_context&, libtorrent::settings_interface const&, libtorrent::counters&)>;
using SessionParams = libtorrent::session_params;
using Session = libtorrent::session;
using AddTorrentParams = libtorrent::add_torrent_params;
using TorrentHandle = libtorrent::torrent_handle;

// Forward declarations for global namespace wrappers
// cxx expects functions in global namespace, all are implemented in bae_storage_cxx_wrappers.cpp
std::unique_ptr<Session> create_session_with_params(std::unique_ptr<SessionParams> params);
Session* get_session_ptr(std::unique_ptr<Session>& sess);
TorrentHandle* session_add_torrent(Session* sess, std::unique_ptr<AddTorrentParams>& params);
bool torrent_has_metadata(TorrentHandle* handle);
int32_t torrent_get_storage_index(TorrentHandle* handle);
int32_t torrent_get_piece_length(TorrentHandle* handle);
int64_t torrent_get_total_size(TorrentHandle* handle);
int32_t torrent_get_num_pieces(TorrentHandle* handle);
bool torrent_have_piece(TorrentHandle* handle, int32_t piece_index);

// Functions wrapped for cxx bridge (implemented in bae_storage_cxx_wrappers.cpp)
// These use cxx Rust types and convert to C++ types
#include "rust/cxx.h"

// Forward declaration - TorrentFileInfo is generated by cxx bridge
struct TorrentFileInfo;
rust::Vec<TorrentFileInfo> torrent_get_file_list(TorrentHandle* handle);

std::unique_ptr<BaeStorageConstructor> create_bae_storage_constructor(
    rust::Fn<rust::Vec<uint8_t>(int32_t, int32_t, int32_t, int32_t)> read_cb,
    rust::Fn<bool(int32_t, int32_t, int32_t, rust::Slice<const uint8_t>)> write_cb,
    rust::Fn<bool(int32_t, int32_t, rust::Slice<const uint8_t>)> hash_cb
);
std::unique_ptr<SessionParams> create_session_params_with_storage(std::unique_ptr<BaeStorageConstructor> disk_io);
std::unique_ptr<AddTorrentParams> parse_magnet_uri(rust::Str magnet, rust::Str save_path);
std::unique_ptr<AddTorrentParams> load_torrent_file(rust::Str file_path, rust::Str save_path);
rust::String torrent_get_name(TorrentHandle* handle);

#endif // BAE_STORAGE_HELPERS_H

